BUG FLAG NAS_NETLINK CHANGED BY SOMEBODY ELSE THAN ME NEW FLAG NAME IS "NAS"

diff --git a/targets/SIMU/EXAMPLES/VIRT_EMUL_1eNB_OAI_LITE/start_one_eNB_multi_UE_nas b/targets/SIMU/EXAMPLES/VIRT_EMUL_1eNB_OAI_LITE/start_one_eNB_multi_UE_nas
--- a/targets/SIMU/EXAMPLES/VIRT_EMUL_1eNB_OAI_LITE/start_one_eNB_multi_UE_nas
+++ b/targets/SIMU/EXAMPLES/VIRT_EMUL_1eNB_OAI_LITE/start_one_eNB_multi_UE_nas
@@ -1,14 +1,19 @@
 #!/bin/bash
 echo "Bash version ${BASH_VERSION}..."
 
+
+#------------------------------------------------
+MAKE_IP_DRIVER_TARGET="naslite_netlink_ether"
+MAKE_LTE_ACCESS_STRATUM_TARGET="oaisim"
+IP_DRIVER_NAME=oai_nw_drv
+#------------------------------------------------
 declare -a NAS_IMEI=( 3 9 1 8 3 6 6 2 0 0 0 0 0 0 )
 # first value is for ENB, then UE0, UE1, etc.
 declare -a MARKING=( 1 2 3 4 5 6 7 8 9 10 11 12 14 15 16 )
 #declare -a PORT_RANGE=( 0:0 40000:40999 41000:41999 42000:42999 43000:43999 )
-
 # BE CAREFULL MAY NOT WORK WITH OTHER VALUES (TO DO)
 declare -i NUM_ENB=1
-
+#------------------------------------------------
 # Notes:
 # We would like to remove the ipv4 addresses swap in the IP driver code for oai virtualized.
 # Let's say oai0 has ipv4 @ 10.0.1.1, oai1 has ipv4 @ 10.0.2.2 etc.
@@ -170,6 +175,155 @@ declare -i NUM_ENB=1
 
 #
 
+###########################################################
+IPTABLES=/sbin/iptables
+THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
+declare -x OPENAIR_DIR=""
+declare -x OPENAIR1_DIR=""
+declare -x OPENAIR2_DIR=""
+declare -x OPENAIR3_DIR=""
+declare -x OPENAIR_TARGETS=""
+###########################################################
+
+
+black='\E[30m'
+red='\E[31m'
+green='\E[32m'
+yellow='\E[33m'
+blue='\E[34m'
+magenta='\E[35m'
+cyan='\E[36m'
+white='\E[37m'
+
+ROOT_UID=0
+E_NOTROOT=67
+
+
+cecho()   # Color-echo
+          # arg1 = message
+          # arg2 = color
+{
+local default_msg="No Message."
+    message=${1:-$default_msg}
+    color=${2:-$black}
+    echo -e "$color"
+    echo -n "$message"
+    tput sgr0
+    echo
+    return
+}
+
+echo_error() {
+local my_string=""
+  until [ -z "$1" ]
+  do
+    my_string="$my_string$1"
+    shift
+  done
+  cecho "$my_string" $red
+}
+
+echo_warning() {
+local my_string=""
+  until [ -z "$1" ]
+  do
+    my_string="$my_string$1"
+    shift
+  done
+  cecho "$my_string" $yellow
+}
+
+echo_success() {
+local my_string=""
+  until [ -z "$1" ]
+  do
+    my_string="$my_string$1"
+    shift
+  done
+  cecho "$my_string" $green
+}
+
+set_openair() {
+    path=`pwd`
+    declare -i length_path
+    declare -i index
+    length_path=${#path}
+
+    index=`echo $path | grep -b -o 'targets' | cut -d: -f1`
+    #echo ${path%$token*}
+    if [[ $index -lt $length_path  && index -gt 0 ]]
+       then
+           declare -x OPENAIR_DIR
+           index=`expr $index - 1`
+           openair_path=`echo $path | cut -c1-$index`
+           #openair_path=`echo ${path:0:$index}`
+           export OPENAIR_DIR=$openair_path
+           export OPENAIR1_DIR=$openair_path/openair1
+           export OPENAIR2_DIR=$openair_path/openair2
+           export OPENAIR3_DIR=$openair_path/openair3
+           export OPENAIR_TARGETS=$openair_path/targets
+           return 0
+    fi
+    return -1
+}
+
+bash_exec() {
+  output=$($1 2>&1)
+  result=$?
+  if [ $result -eq 0 ]
+     then
+        echo_success "$1"
+     else
+        echo_error "$1: $output"
+  fi
+}
+
+wait_process_started () {
+  if  [ -z "$1" ]
+  then
+    echo_error "WAITING FOR PROCESS START: NO PROCESS"
+    return 1
+  fi
+  ps -C $1 > /dev/null 2>&1
+  while [ $? -ne 0 ]; do
+    echo_warning "WAITING FOR $1 START"
+    sleep 2
+    ps -C $1 > /dev/null 2>&1
+  done
+  echo_success "PROCESS $1 STARTED"
+  return 0
+}
+
+assert() {
+  # If condition false
+  # exit from script with error message
+  E_PARAM_ERR=98
+  E_PARAM_FAILED=99
+  
+  if [ -z "$2" ] # Not enought parameters passed.
+  then
+    return $E_PARAM_ERR
+  fi
+  
+  lineno=$2
+  if [ ! $1 ]
+  then
+    echo "Assertion failed:  \"$1\""
+    echo "File \"$0\", line $lineno"
+    exit $E_ASSERT_FAILED
+  fi
+}
+
+
+
+set_openair
+cecho "OPENAIR_DIR     = $OPENAIR_DIR" $green
+cecho "OPENAIR1_DIR    = $OPENAIR1_DIR" $green
+cecho "OPENAIR2_DIR    = $OPENAIR2_DIR" $green
+cecho "OPENAIR3_DIR    = $OPENAIR3_DIR" $green
+cecho "OPENAIR_TARGETS = $OPENAIR_TARGETS" $green
+
+
 declare -i NUM_MOBILES
 declare -i INSTANCE
 declare -i IP_SOURCE
@@ -178,10 +332,16 @@ declare -i IP
 declare -i RB_ID
 declare -i CLASSIFIER_ID
 
-
-iptables -t mangle --flush
-iptables -t nat    --flush
-iptables -t filter --flush
+bash_exec "ip route flush cache"
+bash_exec "$IPTABLES -P INPUT ACCEPT"
+bash_exec "$IPTABLES -F INPUT"
+bash_exec "$IPTABLES -P OUTPUT ACCEPT"
+bash_exec "$IPTABLES -F OUTPUT"
+bash_exec "$IPTABLES -P FORWARD DROP"
+bash_exec "$IPTABLES -F FORWARD"
+bash_exec "$IPTABLES -t nat    -F"
+bash_exec "$IPTABLES -t mangle -F"
+bash_exec "$IPTABLES -t filter -F"
 
 
 NUM_MOBILES=$1
@@ -202,26 +362,33 @@ do
 #     ip route del table $i_p1
 
     echo "ip link set oai$i down"
-    ip link set oai$i down
+    bash_exec "ip link set oai$i down"
 done
 
 
 
-echo "Bringup eNB interface"
+echo "Bringup OAI network interfaces"
+
+bash_exec "rmmod $IP_DRIVER_NAME"
+cecho "make $MAKE_IP_DRIVER_TARGET $MAKE_LTE_ACCESS_STRATUM_TARGET....." $green
+bash_exec "make $MAKE_IP_DRIVER_TARGET $MAKE_LTE_ACCESS_STRATUM_TARGET"
+bash_exec "insmod  $OPENAIR2_DIR/NAS/DRIVER/LITE/$IP_DRIVER_NAME.ko oai_nw_drv_IMEI=${NAS_IMEI[0]},${NAS_IMEI[1]},${NAS_IMEI[2]},${NAS_IMEI[3]},${NAS_IMEI[4]},${NAS_IMEI[5]},${NAS_IMEI[6]},${NAS_IMEI[7]},${NAS_IMEI[8]},${NAS_IMEI[9]},${NAS_IMEI[10]},${NAS_IMEI[11]},${NAS_IMEI[12]},${NAS_IMEI[13]}"
 
 
-rmmod nasmesh
-make  naslite_netlink_ether oaisim
-#insmod $OPENAIR2_DIR/NAS/DRIVER/LITE/nasmesh.ko nas_IMEI=3,9,1,8,3,6,6,2,0,0,0,0,0,0
-#insmod $OPENAIR2_DIR/NAS/DRIVER/LITE/nasmesh.ko nas_IMEI=${NAS_IMEI[0]},${NAS_IMEI[1]},${NAS_IMEI[2]},${NAS_IMEI[3]},${NAS_IMEI[4]},${NAS_IMEI[5]},${NAS_IMEI[6]},${NAS_IMEI[7]},${NAS_IMEI[8]},${NAS_IMEI[9]},${NAS_IMEI[10]},${NAS_IMEI[11]},${NAS_IMEI[12]}, ${NAS_IMEI[13]}
-insmod $OPENAIR2_DIR/NAS/DRIVER/LITE/nasmesh.ko nas_IMEI=${NAS_IMEI[0]},${NAS_IMEI[1]},${NAS_IMEI[2]},${NAS_IMEI[3]},${NAS_IMEI[4]},${NAS_IMEI[5]},${NAS_IMEI[6]},${NAS_IMEI[7]},${NAS_IMEI[8]},${NAS_IMEI[9]},${NAS_IMEI[10]},${NAS_IMEI[11]},${NAS_IMEI[12]},${NAS_IMEI[13]}
 
-ip addr add dev eth2 192.168.14.145/24 broadcast 192.168.14.255
-ip route add 192.168.14.0/24 dev eth2
-ip route add 224.0.0.160/28 dev eth2
+#bash_exec "rmmod nasmesh
+#bash_exec "make  naslite_netlink_ether oaisim
+##insmod $OPENAIR2_DIR/NAS/DRIVER/LITE/nasmesh.ko nas_IMEI=3,9,1,8,3,6,6,2,0,0,0,0,0,0
+##insmod $OPENAIR2_DIR/NAS/DRIVER/LITE/nasmesh.ko nas_IMEI=${NAS_IMEI[0]},${NAS_IMEI[1]},${NAS_IMEI[2]},${NAS_IMEI[3]},${NAS_IMEI[4]},${NAS_IMEI[5]},${NAS_IMEI[6]},${NAS_IMEI[7]},${NAS_IMEI[8]},${NAS_IMEI[9]},${NAS_IMEI[10]},${NAS_IMEI[11]},${NAS_IMEI[12]}, ${NAS_IMEI[13]}
+#insmod $OPENAIR2_DIR/NAS/DRIVER/LITE/nasmesh.ko nas_IMEI=${NAS_IMEI[0]},${NAS_IMEI[1]},${NAS_IMEI[2]},${NAS_IMEI[3]},${NAS_IMEI[4]},${NAS_IMEI[5]},${NAS_IMEI[6]},${NAS_IMEI[7]},${NAS_IMEI[8]},${NAS_IMEI[9]},${NAS_IMEI[10]},${NAS_IMEI[11]},${NAS_IMEI[12]},${NAS_IMEI[13]}
 
 
+#ip addr add dev eth2 192.168.14.145/24 broadcast 192.168.14.255
+#ip route add 192.168.14.0/24 dev eth2
 #ip route add 224.0.0.160/28 dev eth2
+
+
+##ip route add 224.0.0.160/28 dev eth2
 
 NUM_MOBILES=$1
 IP=1
@@ -233,27 +400,21 @@ IP=1
 ########################
 for ((i=0 ; i < `expr $NUM_MOBILES + $NUM_ENB`; i++ ))
 do
-    echo "ip link set oai$i broadcast ff:ff:ff:ff:ff:ff"
-    ip link set oai$i broadcast ff:ff:ff:ff:ff:ff
-
-    echo "ip link set oai$i up"
-    ip link set oai$i up
+    bash_exec "ip link set oai$i broadcast ff:ff:ff:ff:ff:ff"
+    bash_exec "ip link set oai$i up"
     sleep 1
 
-    echo "ifconfig oai$i 10.0.$IP.$IP netmask 255.255.255.0 broadcast 10.0.$IP.255"
-    ifconfig oai$i 10.0.$IP.$IP netmask 255.255.255.0 broadcast 10.0.$IP.255
+    bash_exec "ifconfig oai$i 10.0.$IP.$IP netmask 255.255.255.0 broadcast 10.0.$IP.255"
 
     sleep 1
-    echo "ip addr add dev oai$i 2001:$IP::$IP/64"
-    ip addr add dev oai$i 2001:$IP::$IP/64
+    bash_exec "ip addr add dev oai$i 2001:$IP::$IP/64"
 
     # avoid arp in virtualization
     for ((j=0 ; j <= $NUM_MOBILES ; j++ ))
     do
         if [[ $i -ne $j ]]
         then
-            echo "ip neigh add to 10.0.$IP.$IP lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$i nud permanent dev oai$j"
-            ip neighbour add to 10.0.$IP.$IP lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$i nud permanent dev oai$j
+            bash_exec "ip neighbour add to 10.0.$IP.$IP lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$i nud permanent dev oai$j"
         fi
     done
     let IP=IP+1
@@ -309,16 +470,12 @@ do
             marksrc16=`printf '%02x' $marksrc`
             let markdst=${MARKING[$dst]}
             markdst16=`printf '%02x' $markdst`
-            echo "iptables -t mangle -A OUTPUT --dst 10.0.$IP_SRC.$IP_DST -j MARK --set-mark 0x$marksrc16$markdst16"
-            iptables -t mangle -A OUTPUT --dst 10.0.$IP_SRC.$IP_DST -j MARK --set-mark 0x$marksrc16$markdst16
-            echo "iptables -t nat -A POSTROUTING -m mark --mark 0x$marksrc16$markdst16 -j SNAT --to 10.0.$IP_DST.$IP_SRC"
-            iptables -t nat -A POSTROUTING -m mark --mark 0x$marksrc16$markdst16 -j SNAT --to 10.0.$IP_DST.$IP_SRC
+            bash_exec "iptables -t mangle -A OUTPUT --dst 10.0.$IP_SRC.$IP_DST -j MARK --set-mark 0x$marksrc16$markdst16"
+            bash_exec "iptables -t nat -A POSTROUTING -m mark --mark 0x$marksrc16$markdst16 -j SNAT --to 10.0.$IP_DST.$IP_SRC"
 
             # we can use same mark since not same path (PREROUTING)
-            echo "iptables -t mangle -A PREROUTING --dst 10.0.$IP_SRC.$IP_DST -j MARK --set-mark 0x$marksrc16$markdst16"
-            iptables -t mangle -A PREROUTING --dst 10.0.$IP_SRC.$IP_DST -j MARK --set-mark 0x$marksrc16$markdst16
-            echo "iptables -t nat -A PREROUTING    -m mark --mark 0x$marksrc16$markdst16 -j DNAT --to 10.0.$IP_DST.$IP_DST"
-            iptables -t nat -A PREROUTING      -m mark --mark 0x$marksrc16$markdst16 -j DNAT --to 10.0.$IP_DST.$IP_DST
+            bash_exec "iptables -t mangle -A PREROUTING --dst 10.0.$IP_SRC.$IP_DST -j MARK --set-mark 0x$marksrc16$markdst16"
+            bash_exec "iptables -t nat -A PREROUTING      -m mark --mark 0x$marksrc16$markdst16 -j DNAT --to 10.0.$IP_DST.$IP_DST"
         fi
     done
 done
@@ -395,23 +552,21 @@ do
         then
             # ON eNB
             let RB_ID=(cx*8)+3
-            $OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c$cx -i$instance -f$CLASSIFIER_ID -z64 -s 10.0.$IP_DEST.$IP_SRC/32   -t 10.0.$IP_SRC.$IP_DEST/32   -r $RB_ID
+            bash_exec "$OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c$cx -i$instance -f$CLASSIFIER_ID -z64 -s 10.0.$IP_DEST.$IP_SRC/32   -t 10.0.$IP_SRC.$IP_DEST/32   -r $RB_ID"
             let CLASSIFIER_ID=CLASSIFIER_ID+2
 
             # ON UE
             let IP_SOURCE=instance+1
             let instance_ue=cx+$NUM_ENB
             RB_ID=3
-            $OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c$instance -i$instance_ue -f$CLASSIFIER_ID -z64 -s 10.0.$IP_SRC.$IP_DEST/32 -t 10.0.$IP_DEST.$IP_SRC/32      -r $RB_ID
+            bash_exec "$OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c$instance -i$instance_ue -f$CLASSIFIER_ID -z64 -s 10.0.$IP_SRC.$IP_DEST/32 -t 10.0.$IP_DEST.$IP_SRC/32      -r $RB_ID"
             let CLASSIFIER_ID=CLASSIFIER_ID+2
 
             # ON eNB
-            echo "ip neigh add to 10.0.$IP_SRC.$IP_DEST lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$instance_ue nud permanent dev oai$instance"
-            ip neighbour add to 10.0.$IP_SRC.$IP_DEST lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$instance_ue nud permanent dev oai$instance
+            bash_exec "ip neighbour add to 10.0.$IP_SRC.$IP_DEST lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$instance_ue nud permanent dev oai$instance"
 
             # ON UE
-            echo "ip neigh add to 10.0.$IP_DEST.$IP_SRC lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$instance nud permanent dev oai$instance_ue"
-            ip neighbour add to 10.0.$IP_DEST.$IP_SRC lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$instance nud permanent dev oai$instance_ue
+            bash_exec "ip neighbour add to 10.0.$IP_DEST.$IP_SRC lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$instance nud permanent dev oai$instance_ue"
         fi
     done
 done
@@ -450,8 +605,7 @@ do
     do
         if [[ $i -ne $j ]]
         then
-            echo "ip neigh add to 10.0.$IP.$IP lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$i nud permanent dev oai$j"
-            ip neighbour add to 10.0.$IP.$IP lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$i nud permanent dev oai$j
+            bash_exec "ip neighbour add to 10.0.$IP.$IP lladdr 00:${NAS_IMEI[0]}${NAS_IMEI[1]}:${NAS_IMEI[2]}${NAS_IMEI[3]}:${NAS_IMEI[4]}${NAS_IMEI[5]}:${NAS_IMEI[6]}${NAS_IMEI[7]}:${NAS_IMEI[8]}$i nud permanent dev oai$j"
         fi
     done
     let IP=IP+1
@@ -460,7 +614,7 @@ done
 # echo "start the emulation with 1eNB and" $1 "UE"
 echo "$OPENAIR_TARGETS/SIMU/USER/oaisim -a -u" $1 ">/dev/null"
 # rm -f oai.log
-$OPENAIR_TARGETS/SIMU/USER/oaisim -a -u $1 > /dev/null
-
+#$OPENAIR_TARGETS/SIMU/USER/oaisim -a -u $1 > /dev/null
+$OPENAIR_TARGETS/SIMU/USER/oaisim -a -u $1 -l 7 
 
 echo "End"
